# Generated by Django 3.0.5 on 2020-04-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('reported_user_id', models.CharField(max_length=12)),
                ('reported_tweet_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Baz',
        ),
    ]
