# Generated by Django 3.0.5 on 2020-05-03 02:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collator', '0003_auto_20200501_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawflag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawflag',
            name='flagger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawflag',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
